# Generated by Django 4.2.16 on 2024-11-06 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 0, 7, 680873)),
        ),
        migrations.AlterField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 0, 7, 680884)),
        ),
    ]
